version: '3.6'

services:
  #postgres database
  database:
    container_name: postgres
    build: ./src/configs/postgres
    ports:
      - "5433:5432"

  #Redis session database
  redis:
    container_name: redis
    image: redis:5.0.3
    ports:
      - "6379:6379"
    
  #expres.js backend server
  backend:
    container_name: express
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/usr/src/backend
    env_file:
      - .env
